version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  backend:
    build: ./back
    container_name: springboot_backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      mysql:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build: ./front
    container_name: angular_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
